--- #YAML:1.0
name: Net-Flickr-RDF
version: 1.92
author:
  - Aaron Straup Cope E<lt>ascope@cpan.orgE<gt>
abstract: a.k.a RDF::Describes::Flickr
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
